In [20]:
import pandas as pd
import numpy as np
import sklearn as sk
import math 

import nltk
# # nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

In [21]:
#I'm using a dictionary corpus
corpus = {"Doc1": "Information Retrieval System",
        "Doc2": "Information about the Human Resource System",
        "Doc3": "Resources allocated to Faculty of Computing Information Centre",
        "Doc4": "Ranked Retrieval Model with High Accuracy",
        "Doc5": "Boolean Retrieval Model has Several Problems"}


# TO USE A LIST CORPUS
# corpus = ["I want to start learning to charge something in life",
# "reading something about life no one else knows",
#  "Never stop learning"]
# corpusDict = {}  
# for i,k in enumerate(corpus):
#         corpusDict["doc"+str(i)] = k
# corpus = corpusDict

In [22]:
def TF(corpus):

    total = set(np.concatenate([ i.split(' ') for  i in  corpus.values()]).flat)

    TC = {}
    for i in corpus.keys():
        wordDict = dict.fromkeys(total, 0)
        for word in corpus[i].split(' '):
            wordDict[word]+=1
        TC[i] = wordDict
        

    logTF = {}
    for i in corpus.keys():
        wordDict = dict.fromkeys(total, 0)
        for word, count in TC[i].items():
            if count > 0:
                wordDict[word] = 1 + math.log10(count)
        logTF[i] = wordDict

    # TF = {}
    # for i in corpus.keys():
    #     wordDict = dict.fromkeys(total, 0)
    #     for word, count in TC[i].items():
    #         if count > 0:
    #             wordDict[word] = count/len(corpus[i].split(' '))
    #     TF[i] = wordDict
    # return(TC,TF,total)

    return(TC,logTF, total)


TC,logTF,total = TF(corpus)
pd.DataFrame([i for i in logTF.values()], index = logTF.keys())
pd.DataFrame([i for i in logTF.values()], index = logTF.keys())

,Boolean,about,High,Several,System,the,Information,of,Ranked,Accuracy,...,to,Human,Model,Resource,Computing,Resources,Retrieval,Centre,allocated,has
Doc1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Doc2,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
Doc3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
Doc4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
Doc5,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

In [23]:
def computeIDF(docList):
    idfDict = dict.fromkeys(docList[0].keys(), 0)
    
    for doc in docList:
        for word, val in doc.items():
            if val > 0:
                idfDict[word] += 1
    print(idfDict)
    for word, val in idfDict.items():
        idfDict[word] = 1+ math.log10( len(docList) / (float(val) ))
        
    return(idfDict)

#inputing our sentences in the log file
idfs = computeIDF(list(TC.values()))
pd.DataFrame([idfs])

{'Boolean': 1, 'about': 1, 'High': 1, 'Several': 1, 'System': 2, 'the': 1, 'Information': 3, 'of': 1, 'Ranked': 1, 'Accuracy': 1, 'with': 1, 'Faculty': 1, 'Problems': 1, 'to': 1, 'Human': 1, 'Model': 2, 'Resource': 1, 'Computing': 1, 'Resources': 1, 'Retrieval': 3, 'Centre': 1, 'allocated': 1, 'has': 1}

,Boolean,about,High,Several,System,the,Information,of,Ranked,Accuracy,...,to,Human,Model,Resource,Computing,Resources,Retrieval,Centre,allocated,has
0,1.69897,1.69897,1.69897,1.69897,1.39794,1.69897,1.221849,1.69897,1.69897,1.69897,...,1.69897,1.69897,1.39794,1.69897,1.69897,1.69897,1.221849,1.69897,1.69897,1.69897

In [24]:
def computeTFIDF(logTF, idfs):
    tfidf = {}
    for word, val in logTF.items():
        
        tfidf[word] = val*idfs[word]
        
    return(tfidf)

tdidf = pd.DataFrame([computeTFIDF(logTF[i], idfs) for i in logTF.keys()], index = logTF.keys())
tdidf

,Boolean,about,High,Several,System,the,Information,of,Ranked,Accuracy,...,to,Human,Model,Resource,Computing,Resources,Retrieval,Centre,allocated,has
Doc1,0.00000,0.00000,0.00000,0.00000,1.39794,0.00000,1.221849,0.00000,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.221849,0.00000,0.00000,0.00000
Doc2,0.00000,1.69897,0.00000,0.00000,1.39794,1.69897,1.221849,0.00000,0.00000,0.00000,...,0.00000,1.69897,0.00000,1.69897,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000
Doc3,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.221849,1.69897,0.00000,0.00000,...,1.69897,0.00000,0.00000,0.00000,1.69897,1.69897,0.000000,1.69897,1.69897,0.00000
Doc4,0.00000,0.00000,1.69897,0.00000,0.00000,0.00000,0.000000,0.00000,1.69897,1.69897,...,0.00000,0.00000,1.39794,0.00000,0.00000,0.00000,1.221849,0.00000,0.00000,0.00000
Doc5,1.69897,0.00000,0.00000,1.69897,0.00000,0.00000,0.000000,0.00000,0.00000,0.00000,...,0.00000,0.00000,1.39794,0.00000,0.00000,0.00000,1.221849,0.00000,0.00000,1.69897

### Normalizing

In [25]:
normalized_corpus = corpus.copy()
for key,value in corpus.items():
    normalized_corpus[key] = value.lower()

# UNCOMMENT TO REMOVE STOP WORDS
# for key, value in normalized_corpus.items():
#     normalized_corpus[key] = value.lower().split()
# for key, value in normalized_corpus.items():
#         normalized_corpus[key] = " ".join([word for word in value if word not in stop_words])
# print(normalized_corpus)


normalized_logTF, norm_total = TF(normalized_corpus)[1:]
normalized_idfs = computeIDF(list(normalized_logTF.values()))
normalized_tdidf = pd.DataFrame([computeTFIDF(normalized_logTF[i], normalized_idfs) for i in normalized_logTF.keys()], index = normalized_logTF.keys())

#length normalization of the tfidf of documents
normalized_length_tdidf =  normalized_tdidf.div(normalized_tdidf.pow(2).sum(axis = 1).pow(0.5), axis = 0)
print(normalized_length_tdidf)

{'computing': 1, 'about': 1, 'accuracy': 1, 'faculty': 1, 'system': 2, 'retrieval': 3, 'information': 3, 'the': 1, 'boolean': 1, 'model': 2, 'resource': 1, 'ranked': 1, 'of': 1, 'problems': 1, 'with': 1, 'centre': 1, 'to': 1, 'human': 1, 'several': 1, 'resources': 1, 'has': 1, 'high': 1, 'allocated': 1}
      computing     about  accuracy  faculty    system  retrieval  \
Doc1    0.00000  0.000000  0.000000  0.00000  0.628959   0.549732
Doc2    0.00000  0.438772  0.000000  0.00000  0.361029   0.000000
Doc3    0.36473  0.000000  0.000000  0.36473  0.000000   0.000000
Doc4    0.00000  0.000000  0.438772  0.00000  0.000000   0.315552
Doc5    0.00000  0.000000  0.000000  0.00000  0.000000   0.315552

      information       the   boolean     model  ...  problems      with  \
Doc1     0.549732  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Doc2     0.315552  0.438772  0.000000  0.000000  ...  0.000000  0.000000
Doc3     0.262303  0.000000  0.000000  0.000000  ...  0.000000  0.000000
Doc4     0.000000  0.000000  0.000000  0.361029  ...  0.000000  0.438772
Doc5     0.000000  0.000000  0.438772  0.361029  ...  0.438772  0.000000

       centre       to     human   several  resources       has      high  \
Doc1  0.00000  0.00000  0.000000  0.000000    0.00000  0.000000  0.000000
Doc2  0.00000  0.00000  0.438772  0.000000    0.00000  0.000000  0.000000
Doc3  0.36473  0.36473  0.000000  0.000000    0.36473  0.000000  0.000000
Doc4  0.00000  0.00000  0.000000  0.000000    0.00000  0.000000  0.438772
Doc5  0.00000  0.00000  0.000000  0.438772    0.00000  0.438772  0.000000

      allocated
Doc1    0.00000
Doc2    0.00000
Doc3    0.36473
Doc4    0.00000
Doc5    0.00000

[5 rows x 23 columns]

### Query Tf-Idf

In [26]:
query = "Information Retrieval"
query = query.lower()

# UNCOMMENT TO REMOVE STOP WORDS FOR QUERY
# remove stop words from query
# query = query.lower().split()
# query = " ".join([word for word in query if word not in stop_words])

queryWordsInDocs = [i for i in norm_total if i in query.lower().split(' ')]
queryWordsNOtInDocs = [i for i in total if i in query.lower().split(' ')]

query_df = pd.DataFrame([i for i in normalized_logTF.values()], index = normalized_logTF.keys())[queryWordsInDocs]
query_norm_tf = TF({"query": query.lower()})[1]["query"]
query_norm_tfidf = pd.DataFrame(computeTFIDF(query_norm_tf, normalized_idfs),index = [0])

# query_tfidf =  query_tfidf[queryWordsInDocs]
query_tfidf =  normalized_length_tdidf[queryWordsInDocs+queryWordsNOtInDocs]

print(query_df,'\n',query_tfidf)
print("\nTF*IDF for the query")
query_norm_tfidf

      retrieval  information
Doc1        1.0          1.0
Doc2        0.0          1.0
Doc3        0.0          1.0
Doc4        1.0          0.0
Doc5        1.0          0.0
       retrieval  information
Doc1   0.549732     0.549732
Doc2   0.000000     0.315552
Doc3   0.000000     0.262303
Doc4   0.315552     0.000000
Doc5   0.315552     0.000000

TF*IDF for the query

   retrieval  information
0   1.221849     1.221849

### Euclidean Similarity & Ranking

In [27]:
# getting educlesian distance with python 
a = pd.DataFrame([np.linalg.norm( query_norm_tfidf - query_tfidf.iloc[i]) for i in range(len(query_tfidf) ) ])

query_tfidf_eucleadian= query_tfidf.copy()
query_tfidf_eucleadian['doc'] = corpus.values()
doc_tfidf =  normalized_tdidf[queryWordsInDocs]
query_tfidf_eucleadian["Eucleadian_distance"] = [np.linalg.norm( query_norm_tfidf - doc_tfidf.iloc[i]) for i in range(len(query_tfidf) ) ]

query_tfidf_eucleadian.sort_values(by = "Eucleadian_distance", ascending = True)

,retrieval,information,doc,Eucleadian_distance
Doc1,0.549732,0.549732,Information Retrieval System,0.000000
Doc2,0.000000,0.315552,Information about the Human Resource System,1.221849
Doc3,0.000000,0.262303,Resources allocated to Faculty of Computing In...,1.221849
Doc4,0.315552,0.000000,Ranked Retrieval Model with High Accuracy,1.221849
Doc5,0.315552,0.000000,Boolean Retrieval Model has Several Problems,1.221849

### Cosine Similarity & Ranking

In [28]:
# Cosine for length-normalized vectors

def cosine_similarity(vec1, vec2):
    # normalize to unit length
    norm_vec1 = vec1 / math.sqrt((vec1**2).sum(axis=1))
    norm_vec2 = vec2 / math.sqrt((vec2**2).sum())
    # compute dot product
    dot_product = np.dot(vec1, vec2)
    return dot_product


query_tfidf_cosine= query_tfidf.copy()
query_tfidf_cosine['doc'] = corpus.values()

#Cosine similarity
query_tfidf_cosine["Cosine_distance"] = [cosine_similarity(query_norm_tfidf, query_tfidf.iloc[i]) for i in range(len(query_tfidf) ) ]

query_tfidf_cosine.sort_values(by = "Cosine_distance", ascending = False)

,retrieval,information,doc,Cosine_distance
Doc1,0.549732,0.549732,Information Retrieval System,[1.3433790197118214]
Doc2,0.000000,0.315552,Information about the Human Resource System,[0.3855569169505533]
Doc4,0.315552,0.000000,Ranked Retrieval Model with High Accuracy,[0.3855569169505533]
Doc5,0.315552,0.000000,Boolean Retrieval Model has Several Problems,[0.3855569169505533]
Doc3,0.000000,0.262303,Resources allocated to Faculty of Computing In...,[0.3204947818701641]

### Pruning with Ranking

In [29]:
#index elimination

new_query = "Information Retrieval System for the Information Retrieve Module"
new_query = new_query.lower()

queryWordsInDocs = list(set([i for i in new_query.split() if i in norm_total]))
queryWordsNOtInDocs = [i for i in new_query.split() if i not in norm_total]

query_df = pd.DataFrame([i for i in normalized_logTF.values()], index = normalized_logTF.keys())[queryWordsInDocs]
#This will output td-ifs for the query and tdidf of 0 colomns droped 
query_norm_tf = TF({"query": ' '.join(queryWordsInDocs)})[1]["query"]
query_norm_tfidf = pd.DataFrame(computeTFIDF(query_norm_tf, normalized_idfs),index = [0])

#This will output td-ifs for the docs and tdidf of 0 colomns droped 
query_tfidf =  normalized_length_tdidf[queryWordsInDocs]

print(query_df)
print("\nTF*IDF for the query")
print(query_norm_tfidf)

# Docs containing many query words 
k = 2
filtering_docs = (query_df).sum(axis = 1).values
new_query_tfidf = query_tfidf.copy()
new_query_tfidf['k'] = (query_df).sum(axis = 1).values
new_query_tfidf['doc'] = corpus.values()
new_query_tfidf = new_query_tfidf[new_query_tfidf['k'] >= k]

# Getting cosine values for filtered docs and sorting by cosine value
print('\n2 best relevant documents')
new_query_tfidf['Cosine'] = pd.DataFrame([cosine_similarity(query_norm_tfidf, new_query_tfidf.iloc[i,:len(query_norm_tfidf.columns)]) for i in range(len(new_query_tfidf) ) ]).values
new_query_tfidf.sort_values(by = "Cosine", ascending = False)
new_query_tfidf[:2]

      the  system  retrieval  information
Doc1  0.0     1.0        1.0          1.0
Doc2  1.0     1.0        0.0          1.0
Doc3  0.0     0.0        0.0          1.0
Doc4  0.0     0.0        1.0          0.0
Doc5  0.0     0.0        1.0          0.0

TF*IDF for the query
       the   system  retrieval  information
0  1.69897  1.39794   1.221849     1.221849

2 best relevant documents

,the,system,retrieval,information,k,doc,Cosine
Doc1,0.000000,0.628959,0.549732,0.549732,3.0,Information Retrieval System,2.222626
Doc2,0.438772,0.361029,0.000000,0.315552,3.0,Information about the Human Resource System,1.635715